### PR TITLE
fix: ios visual viewport

### LINKED ISSUE #1074: visualViewport offset make hide and flip modifiers crazy
### CodePen demo

https://6z5bu.csb.app/
https://codesandbox.io/s/loving-feather-6z5bu

### Steps to reproduce the problem

1. open xcode ios simulator
2. toggle software keyboard
2. focus input
3. scroll up and down, hide attribute is applied when input is in viewport

### What is the expected behavior?

Hide attribute should be applied only when input is out of visible viewport

### What went wrong?

visualViewport offsets breaks hide and flip modifiers

### PR DESCRIPTION
**Pull request by atomiks**
fix #1074

Maybe there is a better hack 🤦

### CODE REVIEW

**Comment by TrySound** [comment]
Can we assume that with scale === 1 offsets are always 0?

**Comment by TrySound** [comment]
This works well for me on iOS and scaled chrome on mac
```
import getWindow from './getWindow.js';
export default function getViewportRect(element) {
  var win = getWindow(element);
  var visualViewport = win.visualViewport;
  if (visualViewport) {
    return {
      width: visualViewport.width,
      height: visualViewport.height,
      x: visualViewport.scale === 1 ? 0 : visualViewport.offsetLeft,
      y: visualViewport.scale === 1 ? 0 : visualViewport.offsetTop,
    };
  } else {
    return {
      width: win.innerWidth,
      height: win.innerHeight,
      x: 0,
      y: 0,
    };
  }
}
```

**Comment by atomiks** [comment]
It's broken on macOS Safari for me.

**Comment by TrySound** [comment]
I see only horizontal offset problem. Same problem in chrome. Maybe positioning need to be tweaked?

**Comment by atomiks** [comment]
https://bugs.webkit.org/show_bug.cgi?id=170981 It's this I think. Safari and Chrome do the opposite thing

**Comment by FezVrasta** [comment]
I think we should merge this PR as is, we can work on a subsequent PR to improve the situation for other browsers. Do everybody agree?

**Comment by TrySound** [comment]
width/height work pretty well. The problem is only zoomed viewport. It does not work without visualViewport aswell. So browser detection is not necessary.

**Comment by atomiks** [comment]
I personally use pinch zoom a lot in Chrome and it's an accessibility problem if the popper shifts incorrectly because of this. Applying to iOS only is the safest solution

**Comment by TrySound** [comment]
ok

**Comment by TrySound** [comment]
Can this be release or there are other issues?

**Comment by atomiks** [comment]
It should be fine, this is a fairly critical issue so hopefully a release today

**Pull request merged**
