### PR TITLE
feat: add `autoWhitelist` option to `flip` modifier

### PR DESCRIPTION
**Pull request by FezVrasta**
This should implement #1062

### CODE REVIEW

**Comment by atomiks** [comment]
Not a fan of the term "whitelist" and it's not descriptive of the type like "placements"

**Comment by FezVrasta** [comment]
Alternatives?

**Comment by atomiks** [comment]
`autoPlacements`?

**Comment by FezVrasta** [comment]
I don’t think it’s very clear, this list is a list of placements that can be resolved to starting from the auto placement.

**Comment by atomiks** [comment]
To me, `autoPlacements` is saying, "use only (or restrict to) these placements for `auto`", which is what the behavior is right?

**Comment by FezVrasta** [comment]
I went with `allowedAutoPlacements`

**Pull request merged**
