### PR TITLE
docs: add 3rd party modifiers page

### PR DESCRIPTION
**Pull request by atomiks**

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks! I updated the text and renamed the section to "Community Modifiers", I think it will help to better engage with the community, may you let me know what do you think about the changes?

**Comment by atomiks** [comment]
Yep, worded much better now! Maybe `popper-modifier` instead of `popperjs-modifier` keyword?

**Comment by FezVrasta** [comment]
I wanted to use the same prefix used by the npm scope, just to keep everything consistent on the platform 🤔

**Comment by atomiks** [comment]
uhmm true 😄 I guess I can rename my package to `popperjs-modifier-max-size`, it's very new anyway.

**Comment by FezVrasta** [comment]
The package name doesn’t matter, is enough to have the keyword in the package list

**Pull request merged**
