### PR TITLE
Update jest-playwright-preset

### PR DESCRIPTION
**Pull request by mmarkelov**
Update `jest-playwright-preset` to fix Webkit issue

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks!!

**Comment by FezVrasta** [comment]
Tests keep hitting `Chromium revision is not downloaded. Run "npm install"` for all 3 browsers. Do you have any clue?

**Comment by mmarkelov** [comment]
@FezVrasta I just tried to run test with travis for all browsers. But I also had problems with it. Only chrome works as expected. I'll check it out.

**Comment by FezVrasta** [comment]
I also encountered this on my local machine a couple of times

**Comment by mmarkelov** [comment]
@FezVrasta youp! me too.  Deleting `node_modules` and rerunning `yarn` again helped. (

**Pull request merged**
