### PR TITLE
fix: documentElement as scrollParent

### LINKED ISSUE #1078: Wrong Popper position in a scrolled content
### CodePen demo

https://codepen.io/alex3ax/pen/qBOONPW

### Steps to reproduce the problem

1. Scroll a little bit down
2. Click on the button
3. The tooltip position is wrong

### What is the expected behavior?

The tooltip should be stuck to the bottom of the button

### What went wrong?

The scrollTop of the ref is always 0 in this example, it looks like the offset calculation can't take scroll into account. 

### Any other comments?

Given such a layout is it possible to configure the Popper behavior correctly without layout changes?

### PR DESCRIPTION
**Pull request by atomiks**
Closes #1078 

🚨We need to make sure this doesn't break Edge (<=2019) because the conditional where I added the new expression was important to it IIRC, we had to fix something

### CODE REVIEW

**Comment by atomiks** [comment]
The tests pass for me locally 😢

**Comment by atomiks** [comment]
Uhmm so the module path being misspelled literally didn't error for me anywhere locally (IDE, `yarn test`, ...) but failed in CI? 🤦‍♂️

**Comment by FezVrasta** [comment]
> Uhmm so the module path being misspelled literally didn't error for me anywhere locally (IDE, `yarn test`, ...) but failed in CI? 🤦‍♂️ 

macOS is not case-sensitive, Linux is

**Comment by FezVrasta** [comment]
Edge 18
image

**Comment by atomiks** [comment]
Okay so...

Edge / IE don't report the actual `.scrollTop` on the body, and in this case, it's the only value we can use to determine scroll position (the window and html aren't being scrolled). This DOM layout is so ridiculous anyway 🤦

**Comment by FezVrasta** [comment]
So, it looks like there is no way to detect `document.body` scroll offsets on IE and Edge <= 18 when the `body` is `position: relative; overflow: auto;`.

I'm going to merge this PR to at least fix the other browsers.

**Pull request merged**
